version: '3'

services:
  nginx:
    build: ./nginx/.
    container_name: sitename_nginx
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
    - ../html:/sitename/html
    - ../static:/sitename/static
    - ./cert:/cert